### ISSUE TITLE
I want to have a fixed start and end

### ISSUE THREAD

**Issue by jision** [saby1101/node-tspsolver#1]
Hii,

Good work on the algo I m using this I would be requiring it to have a fixed starting point .Right now its having a closed loop which is perfect but we want the route to begin at a particular point and send at the same point decided by us

**Comment by saby1101** [comment]
Thanks for the feedback 👍.
From what I understand, you essentially want to fix the destination as well. You can take a look at the second argument ("roundtrip"). Setting it false will fix the source as "0"th point and the destination as the "n-1"th point.
