### ISSUE TITLE
What do the different options mean?

### ISSUE THREAD

**Issue by amahlaka** [saby1101/node-tspsolver#5]
What is the meaning and effect of the options N, T, lambda, and reheatInterval?

how do they affect the accuracy and speed of the calculation?

**Comment by saby1101** [comment]
The algorithm uses the Simulated Annealing with Reheating meta-heuristic to solve TSP. The parameters you mentioned are for controlling the process.
N=number of iterations. Specifying a higher number will make the algorithm run longer but may give better solutions
T=the temperature parameter of the annealing process. Modifying it may change the quality of the solution. The runtime is not affected.
lambda, reheatInterval= Again these are SA related parameters. They don't affect the runtime.
