### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by CoonHouse** [saby1101/node-tspsolver#6]
Hello,
Thanks for your resolver.

I have a question though. 
I have the following "costs" matrix:
```
[
  [0, 8267, 1015, 5017, 5823],
  [8273, 0, 8965, 6264, 10239],
  [982, 8998, 0, 5748, 5495],
  [5017, 5236, 5709, 0, 6983],
  [5778, 10239, 5408, 6989, 0]
]
```
Which gives the following order using the resolver: `0, 2, 3, 1, 4`.
Though what I would expect is: `0, 2, 4, 3, 1`.

And when I add these addresses in the "Google Maps" website the expected order is actually shorter (`22 min. 18,8Km` vs `27 min. 22,2 Km`)

Do you have an explanation for this? Do I have to change some of the options? 

Thanks and regards,

Wilco

**Comment by saby1101** [comment]
It seems you must have used roundrip=false. This essentially fixes the start and end locations (in your case 0 and 4). The algorithm is free to move the other points but not these 2 points. You may want to try with roundtrip=true.

**Comment by CoonHouse** [comment]
@saby1101 
Yes, I did. 
Is there a way to only fix the start address without doing a round-trip?

Regards,
Wilco
